import type {
	AgentClientEvent,
	AgentInstanceLocator,
	AgentModelRefreshResult,
	ArchiveWorkItemInput,
	AuthClientEvent,
	AuthMethodType,
	AuthProviderSummary,
	CacheWarmingSettings,
	CodemodeSettings,
	CodePIddyClientApi,
	ContextCompactionSettings,
	CreateAgentInput,
	CreateWorkItemInput,
	DiagnosticsExportInput,
	DiagnosticsExportResult,
	DiagnosticsInfo,
	ExtensionUiResponseInput,
	ForkAgentSessionInput,
	InvokeAgentBuiltinCommandInput,
	LlamaCppActionEvent,
	McpActionInput,
	McpProjectOverrideInput,
	McpProjectOverrideLocator,
	McpServerInput,
	PermissionDefaults,
	ProviderInput,
	RenameWorkItemInput,
	ResetAgentInput,
	RunLlamaCppActionInput,
	SaveLlamaCppConfigInput,
	SendAgentPromptInput,
	SetAgentModelInput,
	SetAgentModelScopeInput,
	SetAgentThinkingInput,
	SetProjectTrustInput,
	SetRoleSkillAssignmentsInput,
	ShareAgentSessionResult,
	ShareSettingsStatus,
	SwitchAgentSessionInput,
	TerminalClientEvent,
	TerminalResizeInput,
	TerminalStartInput,
	TerminalWriteInput,
} from "@codepiddy/shared";
import { contextBridge, ipcRenderer } from "electron";

const channels = {
	abortAgent: "codepiddy:agent:abort",
	reconnectAgent: "codepiddy:agent:reconnect",
	compactAgent: "codepiddy:agent:compact",
	invokeAgentBuiltinCommand: "codepiddy:agent:command:invoke",
	cloneAgentSession: "codepiddy:agent:session:clone",
	getAgentSessionSnapshot: "codepiddy:agent:session:get",
	forkAgentSession: "codepiddy:agent:session:fork",
	shareAgentSession: "codepiddy:agent:session:share",
	listAgentSessions: "codepiddy:agent:session:list",
	newAgentSession: "codepiddy:agent:session:new",
	switchAgentSession: "codepiddy:agent:session:switch",
	deleteAgentSession: "codepiddy:agent:session:delete",
	importAgentSession: "codepiddy:agent:session:import",
	getAgentSessionStats: "codepiddy:agent:session:stats",
	listAuthProviders: "codepiddy:auth:providers",
	startAuthLogin: "codepiddy:auth:login:start",
	respondAuthPrompt: "codepiddy:auth:login:respond",
	cancelAuthLogin: "codepiddy:auth:login:cancel",
	logoutAuthProvider: "codepiddy:auth:logout",
	authEvent: "codepiddy:auth:event",
	resetAgent: "codepiddy:agent:reset",
	activateAgent: "codepiddy:agent:activate",
	agentEvent: "codepiddy:agent:event",
	archiveWorkItem: "codepiddy:work-item:archive",
	createAgent: "codepiddy:agent:create",
	createWorkItem: "codepiddy:work-item:create",
	renameWorkItem: "codepiddy:work-item:rename",
	deleteWorkItem: "codepiddy:work-item:delete",
	getAgentModelSelection: "codepiddy:agent:model:get",
	getAgentModelScope: "codepiddy:agent:model:scope:get",
	refreshAgentModelScope: "codepiddy:agent:model:scope:refresh",
	getAgentCommands: "codepiddy:agent:commands:get",
	getProjectWriteLeaseStatus: "codepiddy:write-lease:get",
	clearStaleProjectWriteLease: "codepiddy:write-lease:clear-stale",
	setAgentModel: "codepiddy:agent:model:set",
	setAgentModelScope: "codepiddy:agent:model:scope:set",
	setAgentThinking: "codepiddy:agent:thinking:set",
	getProjectTrustStatus: "codepiddy:project:trust:get",
	setProjectTrust: "codepiddy:project:trust:set",
	listRecentProjects: "codepiddy:project:recent:list",
	getStartupProject: "codepiddy:project:startup",
	closeProject: "codepiddy:project:close",
	openProject: "codepiddy:project:open",
	openRecentProject: "codepiddy:project:recent:open",
	forgetRecentProject: "codepiddy:project:recent:forget",
	openWorkItemFolder: "codepiddy:work-item:open-folder",
	getProjectUiState: "codepiddy:ui:project:get",
	saveProjectUiState: "codepiddy:ui:project:save",
	getAgentUiState: "codepiddy:ui:agent:get",
	saveAgentUiState: "codepiddy:ui:agent:save",
	refreshProject: "codepiddy:project:refresh",
	restoreWorkItem: "codepiddy:work-item:restore",
	respondToExtensionUi: "codepiddy:agent:extension-ui-response",
	getPendingPermissionRequest: "codepiddy:agent:permission:get-pending",
	settingsClearTavily: "codepiddy:settings:tavily:clear",
	settingsGetTavily: "codepiddy:settings:tavily:get",
	settingsListSkills: "codepiddy:settings:skills:list",
	settingsGetRoleSkills: "codepiddy:settings:role-skills:get",
	settingsSetRoleSkills: "codepiddy:settings:role-skills:set",
	settingsOpenPiConfig: "codepiddy:settings:pi-config:open",
	settingsOpenPermissionPolicy: "codepiddy:settings:permission-policy:open",
	settingsOpenProjectSkills: "codepiddy:settings:project-skills:open",
	settingsOpenBuiltinSkills: "codepiddy:settings:builtin-skills:open",
	settingsShareGet: "codepiddy:settings:share:get",
	settingsShareChooseGitHubCli: "codepiddy:settings:share:github-cli:choose",
	settingsShareSetGitHubCliPath: "codepiddy:settings:share:github-cli:set",
	openExternalUrl: "codepiddy:app:open-external-url",
	settingsGetPermissions: "codepiddy:settings:permissions:get",
	settingsSetPermissions: "codepiddy:settings:permissions:set",
	settingsSaveTavily: "codepiddy:settings:tavily:save",
	settingsSaveShell: "codepiddy:settings:shell:save",
	settingsSaveCacheWarming: "codepiddy:settings:cache-warming:save",
	settingsSaveContextCompaction: "codepiddy:settings:context-compaction:save",
	settingsSaveCodemode: "codepiddy:settings:codemode:save",
	settingsListMcp: "codepiddy:settings:mcp:list",
	settingsSaveMcp: "codepiddy:settings:mcp:save",
	settingsDeleteMcp: "codepiddy:settings:mcp:delete",
	settingsSaveMcpOverride: "codepiddy:settings:mcp:override:save",
	settingsDeleteMcpOverride: "codepiddy:settings:mcp:override:delete",
	settingsMcpAction: "codepiddy:settings:mcp:action",
	settingsListProviders: "codepiddy:settings:providers:list",
	settingsSaveProvider: "codepiddy:settings:providers:save",
	settingsDeleteProvider: "codepiddy:settings:providers:delete",
	llamaCppConfigGet: "codepiddy:llama-cpp:config:get",
	llamaCppConfigSave: "codepiddy:llama-cpp:config:save",
	llamaCppConfigClear: "codepiddy:llama-cpp:config:clear",
	llamaCppStatus: "codepiddy:llama-cpp:status",
	llamaCppAction: "codepiddy:llama-cpp:action",
	llamaCppSearch: "codepiddy:llama-cpp:search",
	llamaCppDetails: "codepiddy:llama-cpp:details",
	llamaCppEvent: "codepiddy:llama-cpp:event",
	settingsStatus: "codepiddy:settings:status",
	piRuntimeStatus: "codepiddy:pi-runtime:status",
	piRuntimeCheck: "codepiddy:pi-runtime:check",
	piRuntimeInstall: "codepiddy:pi-runtime:install",
	piRuntimeRollback: "codepiddy:pi-runtime:rollback",
	piRuntimeRestart: "codepiddy:pi-runtime:restart",
	diagnosticsInfo: "codepiddy:diagnostics:info",
	diagnosticsExport: "codepiddy:diagnostics:export",
	searchProjectFiles: "codepiddy:project:files:search",
	listWorkspaceDir: "codepiddy:workspace:dir:list",
	readWorkspaceFile: "codepiddy:workspace:file:read",
	startTerminal: "codepiddy:terminal:start",
	writeTerminal: "codepiddy:terminal:write",
	resizeTerminal: "codepiddy:terminal:resize",
	killTerminal: "codepiddy:terminal:kill",
	terminalEvent: "codepiddy:terminal:event",
	sendAgentPrompt: "codepiddy:agent:prompt",
} as const;

const api: CodePIddyClientApi = {
	platform: process.platform,
	listRecentProjects: () => ipcRenderer.invoke(channels.listRecentProjects),
	getStartupProject: () => ipcRenderer.invoke(channels.getStartupProject),
	closeProject: (projectRoot: string) => ipcRenderer.invoke(channels.closeProject, projectRoot),
	openRecentProject: (projectRoot: string) => ipcRenderer.invoke(channels.openRecentProject, projectRoot),
	forgetRecentProject: (projectRoot: string) => ipcRenderer.invoke(channels.forgetRecentProject, projectRoot),
	openProject: () => ipcRenderer.invoke(channels.openProject),
	refreshProject: (projectRoot) => ipcRenderer.invoke(channels.refreshProject, projectRoot),
	createWorkItem: (input: CreateWorkItemInput) => ipcRenderer.invoke(channels.createWorkItem, input),
	archiveWorkItem: (input: ArchiveWorkItemInput) => ipcRenderer.invoke(channels.archiveWorkItem, input),
	restoreWorkItem: (input: ArchiveWorkItemInput) => ipcRenderer.invoke(channels.restoreWorkItem, input),
	renameWorkItem: (input: RenameWorkItemInput) => ipcRenderer.invoke(channels.renameWorkItem, input),
	deleteWorkItem: (input: ArchiveWorkItemInput) => ipcRenderer.invoke(channels.deleteWorkItem, input),
	openWorkItemFolder: (input: ArchiveWorkItemInput) => ipcRenderer.invoke(channels.openWorkItemFolder, input),
	getProjectUiState: (projectRoot: string) => ipcRenderer.invoke(channels.getProjectUiState, projectRoot),
	saveProjectUiState: (state) => ipcRenderer.invoke(channels.saveProjectUiState, state),
	getAgentUiState: (agentInstanceId: string) => ipcRenderer.invoke(channels.getAgentUiState, agentInstanceId),
	saveAgentUiState: (state) => ipcRenderer.invoke(channels.saveAgentUiState, state),
	getAgentModelSelection: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.getAgentModelSelection, input),
	getAgentModelScope: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.getAgentModelScope, input),
	refreshAgentModelScope: (input: AgentInstanceLocator): Promise<AgentModelRefreshResult> =>
		ipcRenderer.invoke(channels.refreshAgentModelScope, input),
	getAgentCommands: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.getAgentCommands, input),
	getProjectWriteLeaseStatus: (projectId: string) =>
		ipcRenderer.invoke(channels.getProjectWriteLeaseStatus, projectId),
	clearStaleProjectWriteLease: (projectId: string) =>
		ipcRenderer.invoke(channels.clearStaleProjectWriteLease, projectId),
	setAgentModel: (input: SetAgentModelInput) => ipcRenderer.invoke(channels.setAgentModel, input),
	setAgentModelScope: (input: SetAgentModelScopeInput) => ipcRenderer.invoke(channels.setAgentModelScope, input),
	setAgentThinking: (input: SetAgentThinkingInput) => ipcRenderer.invoke(channels.setAgentThinking, input),
	getProjectTrustStatus: (projectRoot: string) => ipcRenderer.invoke(channels.getProjectTrustStatus, projectRoot),
	setProjectTrust: (input: SetProjectTrustInput) => ipcRenderer.invoke(channels.setProjectTrust, input),
	createAgent: (input: CreateAgentInput) => ipcRenderer.invoke(channels.createAgent, input),
	activateAgent: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.activateAgent, input),
	sendAgentPrompt: (input: SendAgentPromptInput) => ipcRenderer.invoke(channels.sendAgentPrompt, input),
	abortAgent: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.abortAgent, input),
	reconnectAgent: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.reconnectAgent, input),
	compactAgent: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.compactAgent, input),
	invokeAgentBuiltinCommand: (input: InvokeAgentBuiltinCommandInput) =>
		ipcRenderer.invoke(channels.invokeAgentBuiltinCommand, input),
	cloneAgentSession: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.cloneAgentSession, input),
	getAgentSessionSnapshot: (input: AgentInstanceLocator) =>
		ipcRenderer.invoke(channels.getAgentSessionSnapshot, input),
	listAgentSessions: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.listAgentSessions, input),
	newAgentSession: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.newAgentSession, input),
	switchAgentSession: (input: SwitchAgentSessionInput) => ipcRenderer.invoke(channels.switchAgentSession, input),
	deleteAgentSession: (input: SwitchAgentSessionInput) => ipcRenderer.invoke(channels.deleteAgentSession, input),
	importAgentSession: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.importAgentSession, input),
	getAgentSessionStats: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.getAgentSessionStats, input),
	forkAgentSession: (input: ForkAgentSessionInput) => ipcRenderer.invoke(channels.forkAgentSession, input),
	shareAgentSession: (input: AgentInstanceLocator): Promise<ShareAgentSessionResult> =>
		ipcRenderer.invoke(channels.shareAgentSession, input),
	getShareSettings: (): Promise<ShareSettingsStatus> => ipcRenderer.invoke(channels.settingsShareGet),
	chooseGitHubCliPath: (): Promise<string | null> => ipcRenderer.invoke(channels.settingsShareChooseGitHubCli),
	setGitHubCliPath: (path: string | null): Promise<ShareSettingsStatus> =>
		ipcRenderer.invoke(channels.settingsShareSetGitHubCliPath, path),
	listAuthProviders: (): Promise<AuthProviderSummary[]> => ipcRenderer.invoke(channels.listAuthProviders),
	startAuthLogin: (input: { providerId: string; authType: AuthMethodType }): Promise<string> =>
		ipcRenderer.invoke(channels.startAuthLogin, input),
	respondAuthPrompt: (input: {
		requestId: string;
		promptId: string;
		value?: string;
		cancelled?: boolean;
	}): Promise<void> => ipcRenderer.invoke(channels.respondAuthPrompt, input),
	cancelAuthLogin: (requestId: string): Promise<void> => ipcRenderer.invoke(channels.cancelAuthLogin, requestId),
	logoutAuthProvider: (providerId: string): Promise<void> =>
		ipcRenderer.invoke(channels.logoutAuthProvider, providerId),
	onAuthEvent: (listener) => {
		const handler = (_event: Electron.IpcRendererEvent, event: AuthClientEvent) => listener(event);
		ipcRenderer.on(channels.authEvent, handler);
		return () => ipcRenderer.removeListener(channels.authEvent, handler);
	},
	resetAgent: (input: ResetAgentInput) => ipcRenderer.invoke(channels.resetAgent, input),
	respondToExtensionUi: (input: ExtensionUiResponseInput) => ipcRenderer.invoke(channels.respondToExtensionUi, input),
	getPendingPermissionRequest: (input: AgentInstanceLocator) =>
		ipcRenderer.invoke(channels.getPendingPermissionRequest, input),
	searchProjectFiles: (projectRoot: string, query: string) =>
		ipcRenderer.invoke(channels.searchProjectFiles, projectRoot, query),
	listWorkspaceDir: (projectRoot: string, relativeDir: string) =>
		ipcRenderer.invoke(channels.listWorkspaceDir, projectRoot, relativeDir),
	readWorkspaceFile: (projectRoot: string, relativePath: string) =>
		ipcRenderer.invoke(channels.readWorkspaceFile, projectRoot, relativePath),
	startTerminal: (input: TerminalStartInput) => ipcRenderer.invoke(channels.startTerminal, input),
	writeTerminal: (input: TerminalWriteInput) => ipcRenderer.invoke(channels.writeTerminal, input),
	resizeTerminal: (input: TerminalResizeInput) => ipcRenderer.invoke(channels.resizeTerminal, input),
	killTerminal: (terminalId: string) => ipcRenderer.invoke(channels.killTerminal, terminalId),
	getSettingsStatus: () => ipcRenderer.invoke(channels.settingsStatus),
	getPiRuntimeStatus: () => ipcRenderer.invoke(channels.piRuntimeStatus),
	getDiagnosticsInfo: (): Promise<DiagnosticsInfo> => ipcRenderer.invoke(channels.diagnosticsInfo),
	exportDiagnostics: (input: DiagnosticsExportInput): Promise<DiagnosticsExportResult | null> =>
		ipcRenderer.invoke(channels.diagnosticsExport, input),
	checkPiRuntimeUpdate: () => ipcRenderer.invoke(channels.piRuntimeCheck),
	installPiRuntimeUpdate: (version: string) => ipcRenderer.invoke(channels.piRuntimeInstall, version),
	rollbackPiRuntime: () => ipcRenderer.invoke(channels.piRuntimeRollback),
	restartCodePIddy: () => ipcRenderer.invoke(channels.piRuntimeRestart),
	getPermissionDefaults: () => ipcRenderer.invoke(channels.settingsGetPermissions),
	setPermissionDefaults: (input: PermissionDefaults) => ipcRenderer.invoke(channels.settingsSetPermissions, input),
	saveTavilyApiKey: (apiKey: string) => ipcRenderer.invoke(channels.settingsSaveTavily, apiKey),
	clearTavilyApiKey: () => ipcRenderer.invoke(channels.settingsClearTavily),
	getTavilyApiKey: () => ipcRenderer.invoke(channels.settingsGetTavily),
	saveShellPath: (shellPath: string) => ipcRenderer.invoke(channels.settingsSaveShell, shellPath),
	saveCacheWarmingSettings: (input: CacheWarmingSettings) =>
		ipcRenderer.invoke(channels.settingsSaveCacheWarming, input),
	saveContextCompactionSettings: (input: ContextCompactionSettings) =>
		ipcRenderer.invoke(channels.settingsSaveContextCompaction, input),
	saveCodemodeSettings: (input: CodemodeSettings) => ipcRenderer.invoke(channels.settingsSaveCodemode, input),
	listMcpServers: (projectRoot?: string) => ipcRenderer.invoke(channels.settingsListMcp, projectRoot),
	saveMcpServer: (input: McpServerInput) => ipcRenderer.invoke(channels.settingsSaveMcp, input),
	deleteMcpServer: (name: string) => ipcRenderer.invoke(channels.settingsDeleteMcp, name),
	saveMcpProjectOverride: (input: McpProjectOverrideInput) =>
		ipcRenderer.invoke(channels.settingsSaveMcpOverride, input),
	deleteMcpProjectOverride: (input: McpProjectOverrideLocator) =>
		ipcRenderer.invoke(channels.settingsDeleteMcpOverride, input),
	runMcpAction: (input: McpActionInput) => ipcRenderer.invoke(channels.settingsMcpAction, input),
	listProviders: () => ipcRenderer.invoke(channels.settingsListProviders),
	saveProvider: (input: ProviderInput) => ipcRenderer.invoke(channels.settingsSaveProvider, input),
	deleteProvider: (id: string) => ipcRenderer.invoke(channels.settingsDeleteProvider, id),
	getLlamaCppConfig: () => ipcRenderer.invoke(channels.llamaCppConfigGet),
	saveLlamaCppConfig: (input: SaveLlamaCppConfigInput) => ipcRenderer.invoke(channels.llamaCppConfigSave, input),
	clearLlamaCppConfig: () => ipcRenderer.invoke(channels.llamaCppConfigClear),
	getLlamaCppStatus: () => ipcRenderer.invoke(channels.llamaCppStatus),
	runLlamaCppAction: (input: RunLlamaCppActionInput) => ipcRenderer.invoke(channels.llamaCppAction, input),
	searchLlamaCppModels: (query: string) => ipcRenderer.invoke(channels.llamaCppSearch, query),
	getLlamaCppModelDetails: (modelId: string) => ipcRenderer.invoke(channels.llamaCppDetails, modelId),
	onLlamaCppEvent: (listener) => {
		const handler = (_event: Electron.IpcRendererEvent, event: LlamaCppActionEvent) => listener(event);
		ipcRenderer.on(channels.llamaCppEvent, handler);
		return () => ipcRenderer.removeListener(channels.llamaCppEvent, handler);
	},
	listAgentSkills: (projectRoot?: string) => ipcRenderer.invoke(channels.settingsListSkills, projectRoot),
	getRoleSkillAssignments: () => ipcRenderer.invoke(channels.settingsGetRoleSkills),
	setRoleSkillAssignments: (input: SetRoleSkillAssignmentsInput) =>
		ipcRenderer.invoke(channels.settingsSetRoleSkills, input),
	openPiConfigFolder: () => ipcRenderer.invoke(channels.settingsOpenPiConfig),
	openPermissionPolicyFolder: () => ipcRenderer.invoke(channels.settingsOpenPermissionPolicy),
	openProjectSkillsFolder: (projectRoot: string) =>
		ipcRenderer.invoke(channels.settingsOpenProjectSkills, projectRoot),
	openBuiltinSkillsFolder: () => ipcRenderer.invoke(channels.settingsOpenBuiltinSkills),
	openExternalUrl: (url: string) => ipcRenderer.invoke(channels.openExternalUrl, url),
	onAgentEvent: (listener) => {
		const handler = (_event: Electron.IpcRendererEvent, event: AgentClientEvent) => listener(event);
		ipcRenderer.on(channels.agentEvent, handler);
		return () => ipcRenderer.removeListener(channels.agentEvent, handler);
	},
	onTerminalEvent: (listener) => {
		const handler = (_event: Electron.IpcRendererEvent, event: TerminalClientEvent) => listener(event);
		ipcRenderer.on(channels.terminalEvent, handler);
		return () => ipcRenderer.removeListener(channels.terminalEvent, handler);
	},
};

contextBridge.exposeInMainWorld("codepiddy", api);
